name: Run the Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: "REPO"

      - name: Create variables
        run: |
          (
            echo "GITHUB_REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)"
            echo "VERSION=$(echo "${GITHUB_REF_NAME}" | sed -e 's/^v//')"
          ) >> $GITHUB_ENV

      - name: Show variables
        run: env

      - name: Install tools
        run: sudo apt update && sudo apt install python3.11 python-is-python3 debmake dh-python python3-all cmake  python3-setuptools debhelper-compat -y

      - name: Check python ver
        run: python --version

      - name: Run Make
        run: cd REPO && debmake -d -b':python3' -e dr.white.nz@gmail.com -f 'David White'

      - name: Build Package
        run: cd ${{ env.GITHUB_REPO_NAME }}-${{ env.VERSION }} && debuild

      - name: Confirm builds complete
        run: sudo apt install ${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-1_all.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.GITHUB_REPO_NAME }}_${{ env.VERSION }}-1_all.deb
